const Clients = [
  {
    userId: 50,
    name: 'Jovan Stefanović',
    phone: '0691120296',
    email: 'zbni.rs@gmail.com',
    confirmed: true,
  },
  {
    userId: 51,
    name: 'Adrien Stefanović',
    phone: '0605003131',
    email: 'adrienStefanović@gmail.com',
    confirmed: true,
  },
  {
    userId: 52,
    name: 'Alen Stefanović',
    phone: '0601234567',
    email: 'alenstefanovic@gmail.com',
    confirmed: true,
  },
  {
    userId: 53,
    name: 'Željko Sovilj',
    phone: '0646464646',
    email: 'soviljz@gmail.com',
    confirmed: true,
  },
  {
    userId: 54,
    name: 'Darko Sovilj',
    phone: '0605566445',
    email: 'soxdarko@gmail.com',
    confirmed: true,
  },
  {
    userId: 55,
    name: 'Petar Petrović',
    phone: '0665646456',
    email: 'petarpetrovic@gmail.com',
    confirmed: true,
  },
  {
    userId: 56,
    name: 'Mirko Mirković',
    phone: '0638523574',
    email: 'mirkovic@gmail.com',
    confirmed: true,
  },
  {
    userId: 57,
    name: 'Savo Savić',
    phone: '0656485214',
    email: 'ssavic@gmail.com',
    confirmed: true,
  },
  {
    userId: 58,
    name: 'Jovan Stefanović',
    phone: '0691120296',
    email: 'zbni.rs@gmail.com',
    confirmed: true,
  },
  {
    userId: 59,
    name: 'Adrien Stefanović',
    phone: '0605003131',
    email: 'adrienStefanović@gmail.com',
    confirmed: true,
  },
  {
    userId: 60,
    name: 'Alen Stefanović',
    phone: '0601234567',
    email: 'alenstefanovic@gmail.com',
    confirmed: true,
  },
  {
    userId: 61,
    name: 'Željko Sovilj',
    phone: '0646464646',
    email: 'soviljz@gmail.com',
    confirmed: true,
  },
  {
    userId: 62,
    name: 'Darko Sovilj',
    phone: '0605566445',
    email: 'soxdarko@gmail.com',
    confirmed: true,
  },
  {
    userId: 63,
    name: 'Petar Petrović',
    phone: '0665646456',
    email: 'petarpetrovic@gmail.com',
    confirmed: true,
  },
  {
    userId: 64,
    name: 'Mirko Mirković',
    phone: '0638523574',
    email: 'mirkovic@gmail.com',
    confirmed: true,
  },
  {
    userId: 65,
    name: 'Savo Savić',
    phone: '0656485214',
    email: 'ssavic@gmail.com',
    confirmed: true,
  },
  {
    userId: 66,
    name: 'Jovan Stefanović',
    phone: '0691120296',
    email: 'zbni.rs@gmail.com',
    confirmed: true,
  },
  {
    userId: 67,
    name: 'Adrien Stefanović',
    phone: '0605003131',
    email: 'adrienStefanović@gmail.com',
    confirmed: true,
  },
  {
    userId: 68,
    name: 'Alen Stefanović',
    phone: '0601234567',
    email: 'alenstefanovic@gmail.com',
    confirmed: true,
  },
  {
    userId: 69,
    name: 'Željko Sovilj',
    phone: '0646464646',
    email: 'soviljz@gmail.com',
    confirmed: true,
  },
  {
    userId: 70,
    name: 'Darko Sovilj',
    phone: '0605566445',
    email: 'soxdarko@gmail.com',
    confirmed: true,
  },
  {
    userId: 71,
    name: 'Petar Petrović',
    phone: '0665646456',
    email: 'petarpetrovic@gmail.com',
    confirmed: true,
  },
  {
    userId: 72,
    name: 'Mirko Mirković',
    phone: '0638523574',
    email: 'mirkovic@gmail.com',
    confirmed: true,
  },
  {
    userId: 73,
    name: 'Savo Savić',
    phone: '0656485214',
    email: 'ssavic@gmail.com',
    confirmed: true,
  },
  {
    userId: 74,
    name: 'Jovan Stefanović',
    phone: '0691120296',
    email: 'zbni.rs@gmail.com',
    confirmed: true,
  },
  {
    userId: 75,
    name: 'Adrien Stefanović',
    phone: '0605003131',
    email: 'adrienStefanović@gmail.com',
    confirmed: true,
  },
  {
    userId: 76,
    name: 'Alen Stefanović',
    phone: '0601234567',
    email: 'alenstefanovic@gmail.com',
    confirmed: true,
  },
  {
    userId: 77,
    name: 'Željko Sovilj',
    phone: '0646464646',
    email: 'soviljz@gmail.com',
    confirmed: true,
  },
  {
    userId: 78,
    name: 'Darko Sovilj',
    phone: '0605566445',
    email: 'soxdarko@gmail.com',
    confirmed: true,
  },
  {
    userId: 79,
    name: 'Petar Petrović',
    phone: '0665646456',
    email: 'petarpetrovic@gmail.com',
    confirmed: true,
  },
  {
    userId: 80,
    name: 'Mirko Mirković',
    phone: '0638523574',
    email: 'mirkovic@gmail.com',
    confirmed: true,
  },
  {
    userId: 81,
    name: 'Savo Savić',
    phone: '0656485214',
    email: 'ssavic@gmail.com',
    confirmed: true,
  },
];

export default Clients;
